[tool.poetry]
dependencies = {
    "Flask" = "*",
    "Flask-CORS" = "*",
    "requests" = "*",
    "python-dotenv" = "*"
}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
